### ISSUE TITLE
Sugiro colocar alguns emojis nos títulos da descrição do readme

### ISSUE THREAD

**Issue by LigianeBasques** [franciane-lark/challenge-InstitutoEldorado-26-10-2021#2]
Ficaria bem legal se colocasse alguns emojis nos títulos das descrição ou também no corpo do texto do readme.

**Comment by franciane-lark** [comment]
Mana, esse trabalho aí era só um teste. Tem qusee nada, mais pra frente
mexo nele de novo. =) valeu pela dica.

**Comment by LigianeBasques** [comment]
É só um teste que eu estou fazendo com teu repositório. Gostei muito do teu projeto. Parabéns.
